# Generated by Django 6.0.4 on 2026-04-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='grams_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='unit',
            field=models.CharField(choices=[('g', 'Grams'), ('unit', 'Unit (piece)')], default='g', max_length=10),
        ),
    ]
