# Generated by Django 6.0.2 on 2026-04-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_fooditem_grams_per_unit_fooditem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='unit_name',
            field=models.CharField(blank=True, help_text='Display unit like cup, spoon, piece', max_length=20),
        ),
    ]
